apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  labels:
    app: jenkins-pod
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jenkins-app/volume"
